global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:8010']
  - job_name: api
    metrics_path: /prometheus
    static_configs:
      - targets:
          - api:8010